### ISSUE TITLE
Sign up process - Various issues

### ISSUE THREAD

**Issue by 3rror404** [anode-co/AnodeVPN-android#15]
Version: 0.2.65
Android: 8.0.0
Device: Samsung Galaxy S7 Edge (SM-G935F)

1. Install the app
2. Accept permissions requests
3. User is presented with step 1 of sign-up process

### Step 1

The "enter username" input is pre-filled with no visible label to indicate what this input actually is.

![sign-up-01](https://user-images.githubusercontent.com/1102402/139142394-680cffe6-a026-4f18-9d8f-67d2c18146e3.jpg)

When the keyboard is presented, the graphic resizes.

![sign-up-02](https://user-images.githubusercontent.com/1102402/139142635-b406b050-936d-4349-a80a-00ac6188395c.jpg)

### Step 2

1. Again, when the keyboard is presented, the graphic resizes (completely disappears on my device).
2. The email input has no visible label when focused.
3. When the keyboard is presented the password input becomes compressed. When typing in this input the text cannot be seen.

![sign-up-03](https://user-images.githubusercontent.com/1102402/139143449-39f82026-8b44-4e55-82cd-511da074b251.jpg)

### Step 3

After tapping the "Continue" button a toast is displayed, "initial password set"(?), then another toast with an error message "Error: ERROR 500 - Internal Server Error".
Nothing happens after this and you are left at this step.

Despite the 500 error, it does seem that the account is created and can be signed in using the "already have an account? Sign in" button.

**Comment by dkoukoul** [comment]
partially fixed
