### ISSUE TITLE
Device hangs whilst creating wallet

### ISSUE THREAD

**Issue by 3rror404** [anode-co/AnodeVPN-android#17]
Version: 0.2.65
Android: 8.0.0
Device: Samsung Galaxy S7 Edge (SM-G935F)

1. Tap "Wallet" in main menu
2. Tap "Create PKT wallet"
3. Enter new password
4. Tap "Submit"
5. Device hangs for ~30 seconds with no visible feedback. 
- Keyboard remains on screen but can not be interacted with
- All device buttons are unresponsive
6. Success message and seed phrase are then displayed

**Comment by dkoukoul** [comment]
thanks. Unfortunately the create wallet process is taking some time. So to improve the UI experience I' ve added a status bar and switch the background to grey to indicate it is working but put everything in a thread so the main UI thread is not locked.
