### ISSUE TITLE
Input can't be accessed when sending transaction

### ISSUE THREAD

**Issue by 3rror404** [anode-co/AnodeVPN-android#18]
Version: 0.2.65
Android: 8.0.0
Device: Samsung Galaxy S7 Edge (SM-G935F)

When attempting to send PKT from the wallet, the "Receiver's PKT address" input is not visible when the keyboard is presented.

![wallet-send-01](https://user-images.githubusercontent.com/1102402/139149385-8ff0bcbb-5960-4eef-bd18-6b99e1f54fa9.jpg)

There is also a spelling error: "ammount"

**Comment by dkoukoul** [comment]
thanks, this is due to not enough screen size, the address field has been hidden on top. I will make sure to change some margins and the keyboard type on the field to allow for more screen size so the field stays on display.

**Comment by 3rror404** [comment]
I've noticed that on a lot of the layouts it is not possible to scroll within the NestedScrollView that surrounds the main UI elements. This causes issues like this one where views are pushed off screen or views to be compressed like in the ImageViews mentioned in https://github.com/anode-co/AnodeVPN-android/issues/15
