### ISSUE TITLE
ERROR: An error occurred  while executing doInBackground()

### ISSUE THREAD

**Issue by trjate** [anode-co/AnodeVPN-android#19]
After opening the app this message pops up.  After ~ 3 seconds the screen goes black as if the app is reloading and the error reappears before finally disappearing.  Eventually an `Anodium keeps stopping` window pops up.

Android version: 11
OS: Lineage with microG
Phone:  ONEPLUS A3003
![image](https://user-images.githubusercontent.com/12205871/139347477-8abffef3-c6a6-4c18-aff1-38c061f1e68c.png)

**Comment by dkoukoul** [comment]
may I ask if this happened on your first attempt to launch the app. Did you see the prompts for the application permissions?

**Comment by dkoukoul** [comment]
got it, exceptions from httpreq when trying to generate username were not handled correctly.
