### ISSUE TITLE
Can't disconnect VPN

### ISSUE THREAD

**Issue by 3rror404** [anode-co/AnodeVPN-android#20]
Version: 0.2.65
Android: 8.0.0
Device: Samsung Galaxy S7 Edge (SM-G935F)

After clicking the circular button to stop the VPN, the VPN does not seem to properly disconnect.

I see a toast with the message "VPN disconnected" and an overlay requesting a star rating, but the key icon remains in the status bar and I am no longer able to access the internet.

The only way to get out of this state is to the use the "Close app" button in the menu.

![disconnect](https://user-images.githubusercontent.com/1102402/139454643-728315dc-f2bf-4a64-936c-5516da600570.jpg)

**Comment by dkoukoul** [comment]
thanks, found it.
It seems that some times the ParcelFileDescriptor was not being closed and that left the vpn "on".
