### ISSUE TITLE
When pasting an address + other data, spot the address and filter out the other data

### ISSUE THREAD

**Issue by cjdelisle** [anode-co/AnodeVPN-android#25]
The idea is if someone gives you a valid address but with other stuff like "This is my PKT address: "
The app can filter all of that out quite easily.

**Comment by dkoukoul** [comment]
ok I 'll make a regex, do all valid addresses start from pkt1 and have length of 63?

**Comment by cjdelisle** [comment]
There is a legacy format but for the purpose of trimming:
1. anything of 63 alphanumeric chars beginning with pkt1
2. anything of 43 alphanumeric chars beginning with pkt1 (the common case)

Can be trimmed

**Comment by dkoukoul** [comment]
I will test this (^pkt1)([a-zA-Z0-9]{39})
