### ISSUE TITLE
Wallet password visible in keyboard suggestions when typing it

### ISSUE THREAD

**Issue by empewoow** [anode-co/AnodeVPN-android#27]
When typing the wallet password it is visible in the Google keyboard suggestions. See screenshot below. (I typed "my-password" to demonstrate it.) Not sure how other Android keyboards do this, but it feels unsafe to type a password this way.

I'm using version 0.2.113 of the app.

![image](https://user-images.githubusercontent.com/23315837/169821170-4f3fcc04-2697-4f52-bc93-b24d3adf9166.png)

**Comment by dkoukoul** [comment]
Fixed with commit 0d2a28c591e9141be669f8f100b58523cc61f018

**Comment by empewoow** [comment]
Hey @dkoukoul, are you sure? I updated my app, confirmed it's 0.2.115 now, but still it has this issue:

![photo_2022-05-25_21-49-24](https://user-images.githubusercontent.com/23315837/170355459-c19727f4-a552-4899-bc58-0898cd4a00b3.jpg)

**Comment by dkoukoul** [comment]
fixed with 87deb81631044afacd74852729629f18e57a126b

**Comment by empewoow** [comment]
Looks like it is good now!
