### ISSUE TITLE
Cancel button does nothing

### ISSUE THREAD

**Issue by empewoow** [anode-co/AnodeVPN-android#28]
This cancel button does nothing. Using version 0.2.115 of the app.

![image](https://user-images.githubusercontent.com/23315837/170356110-b0e9a002-397b-498c-bfd0-4a7322a3c21f.png)

**Comment by dkoukoul** [comment]
:+1: we need to remove this "Cancel" as the app should not be used if the wallet is not unlocked. I will check in other places as well. thanks

**Comment by dkoukoul** [comment]
removed with commit 4c7061bbab1e7670c1f14d429667ad51c6c5e7f4
