### ISSUE TITLE
VPN disconnects when leaving VPN tab to PKT Wallet tab

### ISSUE THREAD

**Issue by Proskhmer08** [anode-co/AnodeVPN-android#31]
So on the android, after you click Start, VPN starts the authorization, and then it shows VPN Connected. It has a big red button to stop the VPN. But if you click on PKT Wallet or Profile, and return to the VPN tab, the red button changes to Start button indicating that the VPN is no longer connected.

**Comment by dkoukoul** [comment]
Thanks for that, this was happening because it takes sometime for the UI to check the VPN status and update the button status, now we are caching it so it should be almost immediate. Let me know if you are still experiencing it at the last version of the app and I will reopen it if you do.
