### ISSUE TITLE
Can force APP to glitch and show multiple copies of the same transaction when using new UI screen.

### ISSUE THREAD

**Issue by Lexifir** [anode-co/AnodeVPN-android#55]
Issue: Multiple presses can cause an error that glitches the app when using new UI screens.

Version: 0.2.163
Phone: Samsung Galaxy S9+

Issue doesn't appear to cause a crash if not using new UI screens, although will temporarily glitch showing multiple transactions before resolving duplicates.

1. Turn new UI screens on.
2. Go to PKT Wallet.
3. Perform one or multiple presses on 'share' icon.
4. Clear off the pop up menu (which appears many times if spamming the button impatiently)
5.  When screen returns to the Transactions summary - multiple duplicate transactions are shown (if the share button is spammed). (I have a single 2k PKT transfer into Anode VPN, not the 12k shown)

When "Waiting for Network" shows on the top banner \ text bar, the app partially crashes and shows the "Something went wrong dialogue box"
**Note: a single press on the share is also able to glitch the app in the same way multiple presses are**

Turning use "New UI screens" off seems to resolve the issue.

The glitch still allows the user to use the back button on an Android device, and you can get back to the menu system and turn off the new UI screens to then clear the issue.

![Screenshot_20221128-205839_Anode VPN](https://user-images.githubusercontent.com/112382973/204381475-d82d3a43-fb11-4380-b2b3-cb68a324968a.jpg)
![Screenshot_20221128-210457_Anode VPN](https://user-images.githubusercontent.com/112382973/204381478-23716f25-a835-4302-af19-84597aabd226.jpg)

**Comment by dkoukoul** [comment]
This has been resolved with 0.3.3 release
