### ISSUE TITLE
Accessing Wallet Stats can cause a hard crash.

### ISSUE THREAD

**Issue by Lexifir** [anode-co/AnodeVPN-android#56]
Accessing 'Profile' section 'Wallet Stats' and 'Details' can cause a hard crash of the app.

Version 0.2.163
Phone: Samsung S9+

1. Turn off option for new UI screens..
2. Open 'Wallet Stats'
3. Click the three vertical dots (top right)
4.  Select 'Details' option from the menu.

App then crashes after a few seconds and is unrecoverable.

Using New UI screens is slightly more graceful. The pages shows the "Something goes wrong..." dialogue box with the big retry option. Selecting the three dots and pressing details tells the user that it's not implemented yet, but still crashes out after.

![Screenshot_20221128-212219_Anode VPN](https://user-images.githubusercontent.com/112382973/204385654-da6d352a-6342-4b92-ba7f-8ab988efe2b2.jpg)

**Comment by dkoukoul** [comment]
Thanks, this has been fixed now on releases > 0.3
